/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flowvisor_log_Syslog_Facility */

#ifndef _Included_org_flowvisor_log_Syslog_Facility
#define _Included_org_flowvisor_log_Syslog_Facility
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
